// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AffectsController from "./affects_controller"
application.register("affects", AffectsController)

import CategoryBtnController from "./category_btn_controller"
application.register("category-btn", CategoryBtnController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import OpenIncidentsController from "./open_incidents_controller"
application.register("open-incidents", OpenIncidentsController)
